id: kb_rest_sync
namespace: gemini.sync

triggers:
  - id: every_30_minutes
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "*/30 * * * *"

tasks:
  - id: run_connector
    type: io.kestra.plugin.scripts.shell.Commands
    commands:
      - gemini-sync-bridge run --connector connectors/kb-rest.yaml
    retry:
      type: constant
      interval: PT2M
      maxAttempt: 3
