apiVersion: sync.gemini.io/v1alpha1
kind: Connector
metadata:
  name: hr-employees
spec:
  mode: sql_pull
  source:
    type: postgres
    secretRef: hr-db-credentials
    query: SELECT * FROM source_table WHERE updated_at > :watermark
    watermarkField: updated_at
  mapping:
    idField: employee_id
    titleField: full_name
    contentTemplate: '{{ department }} {{ role }} {{ bio }}'
  output:
    bucket: gs://pochert-test-bucket
    prefix: hr-employees
    format: ndjson
  gemini:
    projectId: gemini-enterprise-test-487620
    location: eu
    dataStoreId: hr-ds
  reconciliation:
    deletePolicy: auto_delete_missing
  schedule: 0 */3 * * *
